#mongodb
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stockApp
  server:
    port: 8082

server:
  port: 8082

#logging
logging:
  level:
    root: debug
    com.stocksapp: trace
    com.stocksapp.changeLogs: trace
    org.springframework.data: debug